name: Dannycrafts
author: Dannycrafts
version: 0.0.0

main: com.dannycrafts.plugin.Plugin
load: STARTUP

commands:
    r:
        usage: "r"
        description: The command to be used for the to be implemented regions.